### ISSUE TITLE
selecting text for copying is not possible for active overlay area 

### ISSUE THREAD

**Issue by songaloud** [SamClercky/Dyxitool#5]
**Describe the bug**
I was trying to select and copy a word in the active overlay area, but it was not allowed.

**Expected behavior**
I wish to be able to select and copy texts from the overlay area

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: firefox 
 - Version [72.02 (64-bit)

**Comment by SamClercky** [comment]
Hello Songaloud,

The issue you are talking about is a side effect introduced due to the way the overlay system is being implemented. At this moment I do not see an easy solution that would solve this problem directly.
I would instead propose a system in which you can temporary disable the overlay (Ex. holding Ctrl or a button in the search bar).

Since this is not easy to make intuitive for newcomers, I would need some feedback.

Kind regards,
SamClercky

**Comment by colinstu12** [comment]
Is there still no way to fix this issue? I just discovered this addon as I could really benefit from the overlay, but with no way to still select text without disabling the overlay (which also isn't fast or convenient) is majorly hampering my usage of it.
